name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}        
          username: ${{ secrets.EC2_USER }}    
          key: ${{ secrets.EC2_KEY }}          
          script: |
            if [ ! -d /home/ubuntu/travel/TravelHero ]; then
                git clone https://github.com/ChinmayiBoss/TravelHero.git /home/ubuntu/travel/TravelHero
            fi

            cd /home/ubuntu/travel/TravelHero
            git fetch --all
            git reset --hard origin/main
            npm install --production
            pm2 restart TravelHero || pm2 start index.js --name TravelHero
            pm2 save
